### ISSUE TITLE
Export VOTable Catalog for each run. 

### ISSUE THREAD

**Issue by davepallot** [AusSRC/SoFiAX#5]

**Comment by davepallot** [comment]
Initial commit: f56b0020a4d2471e4cfbba7e5d95851f890d635c
Need to get the ucds and types for the missing columns.

**Comment by SoFiA-Admin** [comment]
UCDs:

- `kin_pa`: `pos.posAng`
- `ra`: `pos.eq.ra`
- `dec`: `pos.eq.dec`
- `l`: `pos.galactic.lon`
- `b`: `pos.galactic.lat`
- `freq`: `em.freq`
- `v_rad`: `spect.dopplerVeloc.radio`
- `v_opt`: `spect.dopplerVeloc.opt`
- `v_app`: `spect.dopplerVeloc`

All of these parameters are of floating-point type. Let me know if I‘ve missed anything.

**Comment by davepallot** [comment]
commit: a522622872d1b8dacc4c83c19d25ca81b8cf516c
