### ISSUE TITLE
Possible typo in sanity check

### ISSUE THREAD

**Issue by SoFiA-Admin** [AusSRC/SoFiAX#6]
There is potentially a typo in the sanity checking code in `merge.py`:

https://github.com/AusSRC/SoFiAX/blob/9abfe58ab264ddf8c079bc60955957e10db07d6b/sofiax/sofiax/merge.py#L72

This was presumably meant to read

```python
diff = abs(f1 - f2) * 100 / ((abs(f1) + abs(f2)) / 2)
```

to calculate the *average* of `f1` and `f2` in the denominator.

**Comment by davepallot** [comment]
Nice pickup. 
I have committed the fix:  7a31eb85d6da044c51c4e495793a3f3140971146
